# -*- coding: utf-8 -*-
"""HW 4 Kyle Arbide Experimental Group

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQ0-0-bfhfNKwbEajVk6FSSpj03rLIlN
"""

import pandas as pd

dfm = pd.read_csv("m_data.csv")

dfw = pd.read_csv("w_data.csv")

dfm.head(5)

dfw.head(5)

dfm.describe()

dfw.describe()

print("Male NAs")
print(dfm.isna().sum())
print("Female NAs")
print(dfw.isna().sum())

# no NA values in the data sets

dfm.bmi.hist()

dfm.steps.hist()

dfw.bmi.hist()

dfw.steps.hist()

# both male and female steps seem normally distributed

import matplotlib as plt

dfm.plot.scatter(x = 'bmi',
                y = 'steps',
                c = 'Black')

dfw.plot.scatter(x = 'bmi',
                 y = 'steps',
                 c = 'Black')

# we notice a shape!! Can we make it clearer?
dfw.plot.scatter(x = 'steps',
                 y = 'bmi',
                 c = 'Black',
                 s = 0.5)

# the imagine is a little clearer, but can we flip it?

dfw.plot.scatter(x = 'steps',
                 y = 'bmi',
                 c = 'Black',
                 s = 0.5).invert_yaxis()

# and for male?
dfm.plot.scatter(x = 'steps',
                 y = 'bmi',
                 c = 'Black',
                 s = 0.5).invert_yaxis()

print(dfm.corr())
print(dfw.corr())
# the results here show no coorelation between bmi and steps

# what do these same charts look like with both datasets put together

frames = [dfm,dfw]

dfAll = pd.concat(frames)
dfAll.head(10)

dfAll.describe()

dfAll.bmi.hist()

dfAll.steps.hist()

dfAll.plot.scatter(x = 'steps',
                 y = 'bmi',
                 c = 'Black',
                 s = 0.5).invert_yaxis()
# image still apears

print(dfAll.corr())

# there is still no correlation between steps and bmi