# -*- coding: utf-8 -*-
"""Homework 1 - Kyle Arbide

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pI6G5K26yKujUojRe4dfym2fiJyZCsPI
"""

#Import student_database
student_database = [
                    {'name':'john doe','id': 12345, 'courses':["MTH1","MTH2"]},
                     {'name':'jane doe','id': 44444, 'courses':["ENG1","ENG2"]},
                    {'name':'moe doe','id': 45674, 'courses':["ENG1"]}
]
print(student_database)

# Register a new student
def register(new_name,new_id):
  new_id = int(new_id)    #changes the string to an integer so all the id's are in the same format
  student_list = [value for elem in student_database
                  for value in elem.values()]
  if new_id in student_list:                     #Checks to see if the inputed ID is in database
    print("This ID is already in the database")
  else:            
    if new_id < 10000:                        # checks to see if inputed ID is 5 digits
      print("Id must be 5 digits")
    elif new_id > 99999:
      print("Id must be 5 digits")
    else:
      new_student = {'name':new_name,'id': new_id}
      student_database.append(new_student)


register("Kyle",10000)

# Find and print student record by name

def find_student(stu_name):
  student_list = [value for elem in student_database
                  for value in elem.values()]
  if stu_name in student_list:            #Checks to see if the inputed name is in database
    for x in student_database: 
      if x["name"] == stu_name:
        if 'courses' in x:                #Checks to see if student is registered for any courses
          print("id:",x['id'])
          print("courses:",x['courses'])
        else:
          print("id:",x['id'])
          print('Student is not registered for any courses')
  else:
    print("Student is not in the database")
find_student("john doe")

# stu_name is currently case sensitive

# Register a student for class
def add_class(stu_id,new_class):
  stu_id = int(stu_id)
  student_list = [value for elem in student_database
                  for value in elem.values()]
  if stu_id in student_list:            #Checks to see if the inputed id is in database
    for x in student_database: 
      if x["id"] == stu_id:
        if 'courses' in x:                  #Different operations based on if the student was or wasnt registered for any other classes
          if new_class in x['courses']:     # Checks if student is already registered for this course
            print("Student is already registered for this course")
          else:
            x['courses'].append(new_class)
        else:
          x['courses'] = [new_class]
  else:
    print("ID is not in the database")
add_class("10000","ABC2")

#new_class is currently case sensitive

# Drop a student from a class
def drop(stu_id,drop_class):
  stu_id = int(stu_id)
  student_list = [value for elem in student_database
                  for value in elem.values()]
  if stu_id in student_list:            #Checks to see if the inputed id is in database
    for x in student_database: 
      if x["id"] == stu_id:
        if 'courses' in x:              #Checks to see if the student is registered for any courses
          if drop_class in x['courses']:        #Checks if student is in the class that was requested to drop
            x['courses'].remove(drop_class)
          else:
            print("Student is not registered for this class")
        else:
           print("Student is not registered for any courses")
  else:
    print("ID is not in the database")
drop(10000,"ABC2")

# drop_class is currently case sensitive