# -*- coding: utf-8 -*-
"""Time Series 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ezGjgO2nD7xrWs9UNyVvMPt7LkBoTTL
"""

!pip install yfinance
import pandas_datareader as web
from pandas_datareader import data as pdr
import yfinance as yfin
import pandas as pd
yfin.pdr_override()

BTC = pdr.get_data_yahoo("BTC-USD", start="2014-01-01", end="2021-10-31")
ETH = pdr.get_data_yahoo("ETH-USD", start="2014-01-01", end="2021-10-31")
DOGE = pdr.get_data_yahoo("DOGE-USD", start="2014-01-01", end="2021-10-31")
SP5 = pdr.get_data_yahoo("^GSPC", start="2014-01-01", end="2021-10-31")

BTC.reset_index(level=0, inplace=True)
ETH.reset_index(level=0, inplace=True)
DOGE.reset_index(level=0, inplace=True)
SP5.reset_index(level=0, inplace=True)

print(BTC.head(1))
print(ETH.head(1))
print(DOGE.head(1))
print(SP5.head(1))

print(BTC.tail(1))
print(ETH.tail(1))
print(DOGE.tail(1))
print(SP5.tail(1))

BTC.describe

BTC.columns

#remove all columns but date and and 'adj close' 
BTC2 = BTC.drop(['Open', 'High', 'Low', 'Close', 'Volume'], axis =1)
ETH2 = ETH.drop(['Open', 'High', 'Low', 'Close', 'Volume'], axis =1)
DOGE2 = DOGE.drop(['Open', 'High', 'Low', 'Close', 'Volume'], axis =1)
SP52 = SP5.drop(['Open', 'High', 'Low', 'Close', 'Volume'], axis =1)

BTC2.info()

ETH2.head(10)

BTC = BTC2.rename(columns={"Adj Close":"Adj_Close_BTC"})
ETH = ETH2.rename(columns={"Adj Close":"Adj_Close_ETH"})
DOGE = DOGE2.rename(columns={"Adj Close":"Adj_Close_DOGE"})
SP5 = SP52.rename(columns={"Adj Close":"Adj_Close_SP5"})

Merged = SP5.merge(ETH, how = 'outer', on = "Date")
Merged = Merged.merge(DOGE, how = 'outer', on = "Date")
Merged = Merged.merge(BTC, how = 'outer', on = "Date")

Merged

Merged['Date']=pd.to_datetime(Merged.Date)

Merged = Merged.sort_values('Date')

Merged = Merged.set_index(Merged['Date'])

Merged =Merged.drop('Date',axis=1)

Merged

import matplotlib.pyplot as plt
import numpy as np

SP5.plot(title="S&P 500 Adjusted Price Over Time")

BTC['Date']=pd.to_datetime(BTC.Date)
BTC = BTC.sort_values('Date')
BTC =BTC.set_index(BTC['Date'])
BTC =BTC.drop('Date',axis=1)

BTC.plot(title="BTC Adjusted Price Over Time", color='red')

ETH['Date']=pd.to_datetime(ETH.Date)
ETH = ETH.sort_values('Date')
ETH =ETH.set_index(ETH['Date'])
ETH =ETH.drop('Date',axis=1)

DOGE['Date']=pd.to_datetime(DOGE.Date)
DOGE = DOGE.sort_values('Date')
DOGE =DOGE.set_index(DOGE['Date'])
DOGE =DOGE.drop('Date',axis=1)

ETH.plot(title="Ethereum Adjusted Price Over Time", color='orange')

DOGE.plot(title="Dogecoin Adjusted Price Over Time", color='green')